all:
	cp crack_attack.py crack_attack
	chmod +x crack_attack
	
	cp attack_server.py attack_server

	chmod +x attack_server

clean:
	rm -f crack_attack attack_server
	rm -f orig_date.gz orig_date_data.h
	rm -f date
	rm -f padded_virus
	rm -f polluted_date
	rm -f virus.c
	rm -f raw_virus
	rm -f session_id.txt
	rm -f secret_key_iv.json
	rm -f sig.bin
	rm -f *.pem
	rm -f worm_gen.cpp
	rm -f worm